package com.mt.lamdatrack.Rate.nodes;

import android.annotation.SuppressLint;
import android.content.Context;
import android.os.AsyncTask;
import android.util.Log;


import com.mt.lamdatrack.R;
import com.mt.lamdatrack.Rate.RatesReq;
import com.mt.lamdatrack.Rate.select.Elements;

import java.util.ArrayList;

public class Rates {

    public static void getAllRates(Context context) {

        JISJFIOSJFIOSFJISFJSIFJSIFJSIFSJFIOSJFISJFSIOFJSIOFJSIOFJSIOFJSIOFJIOJFEIUOWNRFJEWNRFJEN43JRTN43URT438795RY4389RU3JKFDISDMCKLSDNFUIR3HF8ERJF980REJF89ERHUF8U9ERHFGE78RFJHE89RFJEW980FJ3R98 = context;
        KPKKKKLKLKLAAAADWEDWED.KOKPOKOKLKL(JISJFIOSJFIOSFJISFJSIFJSIFJSIFSJFIOSJFISJFSIOFJSIOFJSIOFJSIOFJSIOFJIOJFEIUOWNRFJEWNRFJEN43JRTN43URT438795RY4389RU3JKFDISDMCKLSDNFUIR3HF8ERJF980REJF89ERHUF8U9ERHFGE78RFJHE89RFJEW980FJ3R98);
    }


    static class JFHSDJKFNSJFNSDJFNSDUIFHERUIFHERUFHER7U8FH7ERHF7ERYF798ERYF798ERF7EWRHFUIHRNB43UIR3UIRHNUIRN4UIR43 extends AsyncTask<String, String, String> {

//    load states all with their links href

        @Override
        protected String doInBackground(String... params) {
            Document JNOSDAJNSADJNSDAJNKSDA = null;
            try {
                dksmdksmdksdmskduie43jhrf83u49rhf398f3489tf34890rtu498r4389frufufwerufuf.jkndosajskdno(KJLSDAKLSDKJLKDJLSKDJASNKDJKJN, KOJKOJKOJKJOKLJKLJKLJ);

                JNOSDAJNSADJNSDAJNKSDA = UHUnbnnbsd.sdfdssd(JNOSDAJNSADJNSDAJNKSDA, JISJFIOSJFIOSFJISFJSIFJSIFJSIFSJFIOSJFISJFSIOFJSIOFJSIOFJSIOFJSIOFJIOJFEIUOWNRFJEWNRFJEN43JRTN43URT438795RY4389RU3JKFDISDMCKLSDNFUIR3HF8ERJF980REJF89ERHUF8U9ERHFGE78RFJHE89RFJEW980FJ3R98);

                nnnnndashjbhj(JNOSDAJNSADJNSDAJNKSDA);
                mmmmmsdkjfjkdfsjdsdsj(JNOSDAJNSADJNSDAJNKSDA);

                try {
                    NCDEXrates KSDDDDDDDDDDDFNU43UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS = (NCDEXrates) JISJFIOSJFIOSFJISFJSIFJSIFJSIFSJFIOSJFISJFSIOFJSIOFJSIOFJSIOFJSIOFJIOJFEIUOWNRFJEWNRFJEN43JRTN43URT438795RY4389RU3JKFDISDMCKLSDNFUIR3HF8ERJF980REJF89ERHUF8U9ERHFGE78RFJHE89RFJEW980FJ3R98;
                    KSDDDDDDDDDDDFNU43UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.NcdexRates(KJLSDAKLSDKJLKDJLSKDJASNKDJKJN);
                    KSDDDDDDDDDDDFNU43UUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUUSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS.McxRates(KOJKOJKOJKJOKLJKLJKLJ);
                } catch (Exception LDSADMDDKSALDLADKASLDASKLDKDOKDOIEIOIEMMVVMCKVMCKXVMKVMCKVMCKVMKCVCKVCKVMCKVMCVKCMVKCMVKVMKCMVKMFKMDKFMDKFMEDKRMEKRE) {
                    Log.wtf("Hulk-65", LDSADMDDKSALDLADKASLDASKLDKDOKDOIEIOIEMMVVMCKVMCKXVMKVMCKVMCKVMKCVCKVCKVMCKVMCVKCMVKCMVKVMKCMVKMFKMDKFMDKFMEDKRMEKRE.getMessage());
                }


            } catch (Exception JDASJDIJDISJDISDJSDIDFJ) {
                NCDEXrates MFKDSMFKSMFSDKFDSMFSDKFMSDKFMSDKFMSDKFMSFKMSDKFMSKFMSDFKMSFKSMFKSDMFKSDFMSKFMSKFMSKFMSKFMSKFMSKFMSKFMSKMRFIEJRIEJRIEJRIEJ4R834U83UE83UE834U8JE83JE83UE83UE = (NCDEXrates) JISJFIOSJFIOSFJISFJSIFJSIFJSIFSJFIOSJFISJFSIOFJSIOFJSIOFJSIOFJSIOFJIOJFEIUOWNRFJEWNRFJEN43JRTN43URT438795RY4389RU3JKFDISDMCKLSDNFUIR3HF8ERJF980REJF89ERHUF8U9ERHFGE78RFJHE89RFJEW980FJ3R98;
                MFKDSMFKSMFSDKFDSMFSDKFMSDKFMSDKFMSDKFMSFKMSDKFMSKFMSDFKMSFKSMFKSDMFKSDFMSKFMSKFMSKFMSKFMSKFMSKFMSKFMSKMRFIEJRIEJRIEJRIEJ4R834U83UE83UE834U8JE83JE83UE83UE.FailedToLoad(JDASJDIJDISJDISDJSDIDFJ.getMessage());

            }

            return null;
        }

        private void nnnnndashjbhj(Document kkkkkskdsdsdsdewdefejnvnvnvnvnvbgb) {
            Elements uiojjouijiosfjosfjosjfksjfiosfjskofjsofjsjfhyuirehgyfrnui = kkkkkskdsdsdsdewdefejnvnvnvnvnvbgb.getElementById(JISJFIOSJFIOSFJISFJSIFJSIFJSIFSJFIOSJFISJFSIOFJSIOFJSIOFJSIOFJSIOFJIOJFEIUOWNRFJEWNRFJEN43JRTN43URT438795RY4389RU3JKFDISDMCKLSDNFUIR3HF8ERJF980REJF89ERHUF8U9ERHFGE78RFJHE89RFJEW980FJ3R98.getResources().getString(R.string.jknljnjnk)).getElementsByClass("tableDataBox");
            int i = 0;
            try {
                do {
                    KJLSDAKLSDKJLKDJLSKDJASNKDJKJN.add(new RatesReq("" + uiojjouijiosfjosfjosjfksjfiosfjskofjsofjsjfhyuirehgyfrnui.select("ol").select("li").select("a").get(i).text(),
                            "" + uiojjouijiosfjosfjosjfksjfiosfjskofjsofjsjfhyuirehgyfrnui.select("ol").select("li").select("strong").get(i).text(),
                            "" + uiojjouijiosfjosfjosjfksjfiosfjskofjsofjsjfhyuirehgyfrnui.select("ol").select("li").next().get(i).ownText(),
                            "" + uiojjouijiosfjosfjosjfksjfiosfjskofjsofjsjfhyuirehgyfrnui.select("ol").select("li").select("span").get(i).text()
                    ));
                    i++;
                }
                while (i != -1);
            } catch (Exception e) {
//                    Log.wtf("Hulk-57", e.getMessage());
                i = -1;

            }
        }

        private void mmmmmsdkjfjkdfsjdsdsj(Document pageDocument) {
            Elements UUUUUUUUDCHUSBCHJSBFBWFHBFHEBFHJBHBVFEHJVBFEHJGBGBHGRBG = pageDocument.getElementById(JISJFIOSJFIOSFJISFJSIFJSIFJSIFSJFIOSJFISJFSIOFJSIOFJSIOFJSIOFJSIOFJIOJFEIUOWNRFJEWNRFJEN43JRTN43URT438795RY4389RU3JKFDISDMCKLSDNFUIR3HF8ERJF980REJF89ERHUF8U9ERHFGE78RFJHE89RFJEW980FJ3R98.getResources().getString(R.string.mmmadjja)).getElementsByClass(JISJFIOSJFIOSFJISFJSIFJSIFJSIFSJFIOSJFISJFSIOFJSIOFJSIOFJSIOFJSIOFJIOJFEIUOWNRFJEWNRFJEN43JRTN43URT438795RY4389RU3JKFDISDMCKLSDNFUIR3HF8ERJF980REJF89ERHUF8U9ERHFGE78RFJHE89RFJEW980FJ3R98.getResources().getString(R.string.HJBHJBHJBJHBHJBHJBHJS));
            int i = 0;
            try {
                do {
                    KOJKOJKOJKJOKLJKLJKLJ.add(new RatesReq("" + UUUUUUUUDCHUSBCHJSBFBWFHBFHEBFHJBHBVFEHJVBFEHJGBGBHGRBG.select("ol").select("li").select("a").get(i).text(),
                            "" + UUUUUUUUDCHUSBCHJSBFBWFHBFHEBFHJBHBVFEHJVBFEHJGBGBHGRBG.select("ol").select("li").select("strong").get(i).text(),
                            "" + UUUUUUUUDCHUSBCHJSBFBWFHBFHEBFHJBHBVFEHJVBFEHJGBGBHGRBG.select("ol").select("li").next().get(i).ownText(),
                            "" + UUUUUUUUDCHUSBCHJSBFBWFHBFHEBFHJBHBVFEHJVBFEHJGBGBHGRBG.select("ol").select("li").select("span").get(i).text()
                    ));
                    i++;
                }
                while (i != -1);
            } catch (Exception e) {
                i = -1;

            }
        }


        @SuppressLint("RestrictedApi")
        @Override
        protected void onPostExecute(String JDKASOJDKLASDJAISODJASIODJASIODJSAIDJSAIDJSIODFJIJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE) {
            super.onPostExecute(JDKASOJDKLASDJAISODJASIODJASIODJSAIDJSAIDJSIODFJIJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJJEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE);

        }

    }

    static Context JISJFIOSJFIOSFJISFJSIFJSIFJSIFSJFIOSJFISJFSIOFJSIOFJSIOFJSIOFJSIOFJIOJFEIUOWNRFJEWNRFJEN43JRTN43URT438795RY4389RU3JKFDISDMCKLSDNFUIR3HF8ERJF980REJF89ERHUF8U9ERHFGE78RFJHE89RFJEW980FJ3R98 = null;
    static ArrayList<RatesReq> KJLSDAKLSDKJLKDJLSKDJASNKDJKJN = new ArrayList<>();
    static ArrayList<RatesReq> KOJKOJKOJKJOKLJKLJKLJ = new ArrayList<>();

    public interface NCDEXrates {
        public void NcdexRates(ArrayList<RatesReq> list);

        public void McxRates(ArrayList<RatesReq> list);

        public void FailedToLoad(String error);
    }
}
